version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: capstone_api
    restart: unless-stopped
    depends_on: []
    environment:
      API_KEY: demo_key_123
      LLM_PROVIDER: ollama
      OLLAMA_BASE: http://172.17.0.2:11434
      OLLAMA_CHAT_MODEL: llama3.2:3b
      OLLAMA_EMBED_MODEL: mxbai-embed-large
      EMBED_DIM: "1024"
      DATABASE_URL: postgresql://langflow_user:langflow_password@172.17.0.3:5432/langflow_connect
    ports:
      - "8000:8000"


