version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: langflow-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=langflow_connect
      - POSTGRES_USER=langflow_user
      - POSTGRES_PASSWORD=langflow_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - langflow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langflow_user -d langflow_connect"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: capstone_api
    restart: unless-stopped
    networks:
      - langflow-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      API_KEY: demo_key_123
      LLM_PROVIDER: ollama
      OLLAMA_BASE: http://lfc-ollama:11434
      OLLAMA_CHAT_MODEL: llama3.2:3b
      OLLAMA_EMBED_MODEL: mxbai-embed-large
      EMBED_DIM: "1024"
      DATABASE_URL: postgresql://langflow_user:langflow_password@postgres:5432/langflow_connect
    ports:
      - "8000:8000"

  ollama:
    image: ollama/ollama:latest
    container_name: lfc-ollama
    restart: unless-stopped
    networks:
      - langflow-network
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0

volumes:
  postgres_data:
  ollama_data:

networks:
  langflow-network:
    driver: bridge


