services:
  - type: web
    name: capstone-api
    env: python
    plan: free
    # Use repo root as working dir and reference api/ explicitly for robustness
    buildCommand: pip install --upgrade pip && pip install -r api/requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: API_KEY
        sync: false
services:
- buildCommand: pip install -r requirements.txt
  env: python
  envVars:
  - key: API_KEY
    value: demo_key_123
  - key: PORT
    value: '8000'
  name: capstone-project-api-enhanced
  startCommand: python src/mcp_server_simple_secure.py
  type: web
